export const isoData = [
  { code: 'A.5.1.1',  name: 'İnformasiya təhlükəsizliyi siyasəti', description: 'İnformasiya təhlükəsizliyi üzrə siyasətlər toplusu müəyyən edilməli, rəhbərlik tərəfindən təsdiq edilməli, dərc edilməli və işçilərə və müvafiq kənar tərəflərə çatdırılmalıdır.' },
  { code: 'A.5.1.2',  name: 'İnformasiya təhlükəsizliyi siyasətlərinin nəzərdən keçirilməsi', description: 'İnformasiya təhlükəsizliyi üzrə siyasətlər planlaşdırılmış fasilələrlə və ya onların davamlı uyğunluğunu, adekvatlılığını və səmərəliliyini təmin etmək məqsədilə əhəmiyyətli dəyişikliklər baş verdikdə nəzərdən keçirilməlidir.' },
  { code: 'A.6.1.1',  name: 'İnformasiya təhlükəsizliyi funksiyaları və məsuliyyətləri', description: 'İnformasiya təhlükəsizliyi üzrə bütün öhdəliklər müəyyən edilməli və bölüşdürülməlidir.' },
  { code: 'A.6.1.2',  name: 'Vəzifə bölgüsü', description: 'Təşkilatın aktivlərinin icazəsiz və ya təsadüfən dəyişdirilməsi və ya sui-istifadəsi imkanlarını azaltmaq üçün ziddiyyətli vəzifələr və məsuliyyətlər ayrılmalıdır.' },
  { code: 'A.6.1.3',  name: 'Səlahiyyətli şəxslərlə əlaqə saxlamaq', description: 'Müvafiq orqanlarla uyğun əlaqələr saxlanılmalıdır.' },
  { code: 'A.6.1.4',  name: 'Xüsusi maraq qrupları ilə əlaqə saxlamaq', description: 'Xüsusi maraq qrupları və ya digər xüsusi təhlükəsizlik forumları və peşəkar birliklərlə uyğun əlaqələr saxlanılmalıdır.' },
  { code: 'A.6.1.5',  name: 'Layihənin idarə edilməsində informasiya təhlükəsizliyi', description: 'Layihənin növündən asılı olmayaraq, layihənin idarə edilməsində informasiya təhlükəsizliyinə diqqət yetirilməlidir.' },
  { code: 'A.6.2.1',  name: 'Mobil cihaz siyasəti', description: 'Mobil cihazlardan istifadə zamanı yaranan riskləri idarə etmək üçün siyasət və dəstəkləyici təhlükəsizlik tədbirləri qəbul edilməlidir.' },
  { code: 'A.6.2.2',  name: 'Məsafədən işləmə', description: 'Məsafədən işləmə zamanı əldə edilən, emal edilən və ya saxlanılan məlumatı qorumaq üçün siyasət və dəstəkləyici təhlükəsizlik tədbirləri həyata keçirilməlidir.' },
  { code: 'A.7.1.1',  name: 'İncələmə', description: 'İşə qəbul zamanı bütün namizədlərin bioqrafik məlumatlarının yoxlanılması müvafiq qanunlar, qaydalar və etikaya uyğun olaraq aparılmalıdır.' },
  { code: 'A.7.1.2',  name: 'Əmək müqaviləsinin şərtləri', description: 'İşçilərlə və podratçılarla bağlanan müqavilələrdə onların və təşkilatın informasiya təhlükəsizliyi ilə bağlı öhdəlikləri müəyyən edilməlidir.' },
  { code: 'A.7.2.1',  name: 'Rəhbərliyin səlahiyyətləri', description: 'Rəhbərlik bütün işçilərdən və podratçılardan təşkilatın müəyyən edilmiş siyasətlərinə uyğun olaraq informasiya təhlükəsizliyini tətbiq etməyi tələb etməlidir.' },
  { code: 'A.7.2.2',  name: 'İnformasiyanın nişanlanması və işlənməsi', description: 'Təşkilat tərəfindən qəbul olunmuş təsnifat sxeminə uyğun olaraq, informasiyanın nişanlanması və işlənməsi üçün prosedurlar hazırlanmalıdır.' },
  { code: 'A.7.2.3',  name: 'İntizam prosesi', description: 'İnformasiya təhlükəsizliyi pozuntusuna yol vermiş işçilərə qarşı tədbir görülməsi üçün rəsmi intizam prosesi olmalıdır.' },
  { code: 'A.7.3.1',  name: 'Əmək münasibətlərinə xitam verilməsi və ya dəyişdirilməsi', description: 'İşə xitam verildikdən sonra qüvvədə qalan informasiya təhlükəsizliyi öhdəlikləri işçiyə bildirilməli və icrası təmin edilməlidir.' },
  { code: 'A.8.1.1',  name: 'Aktivlərin inventarlaşdırılması', description: 'İnformasiya və informasiya emalı vasitələri ilə bağlı aktivlər müəyyən edilməli və inventarlaşdırılması aparılmalıdır.' },
  { code: 'A.8.1.2',  name: 'Aktivlərin mülkiyyəti', description: 'İnventarizasiyaya daxil edilmiş aktivlər mülkiyyətdə olmalıdır.' },
  { code: 'A.8.1.3',  name: 'Aktivlərin məqbul istifadəsi', description: 'İnformasiyanın və aktivlərin məqbul istifadəsi qaydaları müəyyən edilməli, sənədləşdirilməli və həyata keçirilməlidir.' },
  { code: 'A.8.1.4',  name: 'Aktivlərin qaytarılması', description: 'Bütün işçilər fəaliyyətə xitam verildikdən sonra mülkiyyətlərindəki bütün təşkilati aktivləri geri qaytarmalıdırlar.' },
  { code: 'A.8.2.1',  name: 'İnformasiyanın təsnifatı', description: 'Məlumat qanuni tələblər, dəyər, əhəmiyyəti baxımından təsnif edilməlidir.' },
  { code: 'A.8.2.2',  name: 'Məlumatın etiketlənməsi', description: 'Məlumatın etiketlənməsi üçün müvafiq prosedurlar qəbul edilmiş təsnifat sxeminə uyğun olaraq həyata keçirilməlidir.' },
  { code: 'A.8.2.3',  name: 'Aktivlərin idarə edilməsi', description: 'Aktivlərin idarə edilməsi prosedurları qəbul edilmiş məlumatların təsnifatı sxeminə uyğun olmalıdır.' },
  { code: 'A.8.3.1',  name: 'Çıxarıla bilən informasiya daşıyıcısının idarə edilməsi', description: 'Çıxarıla bilən informasiya daşıyıcılarının idarə edilməsi üçün prosedurlar həyata keçirilməlidir.' },
  { code: 'A.8.3.2',  name: 'İnformasiya daşıyıcısının utilizasiyası', description: 'İnformasiya daşıyıcıları artıq lazım olmadıqda rəsmi prosedurlarla təhlükəsiz şəkildə utilizasiya edilməlidir.' },
  { code: 'A.8.3.3',  name: 'Fiziki informasiya daşıyıcısının ötürülməsi', description: 'Məlumatı ehtiva edən informasiya daşıyıcısı daşınma zamanı icazəsiz giriş və zədələnmədən qorunmalıdır.' },
  { code: 'A.9.1.1',  name: 'Girişə nəzarət siyasəti', description: 'Girişə nəzarət siyasəti biznes və informasiya təhlükəsizliyi tələbləri əsasında yaradılmalı və nəzərdən keçirilməlidir.' },
  { code: 'A.9.1.2',  name: 'Şəbəkə və şəbəkə xidmətlərinə giriş', description: 'İstifadəçilərə yalnız xüsusi icazə verilmiş şəbəkə və şəbəkə xidmətlərinə giriş icazəsi təmin edilməlidir.' },
  { code: 'A.9.2.1',  name: 'İstifadəçinin qeydiyyatı və qeydiyyatdan çıxarılması', description: 'Giriş hüquqlarının təyin edilməsini təmin etmək üçün istifadəçinin rəsmi qeydiyyat prosesi həyata keçirilməlidir.' },
  { code: 'A.9.2.2',  name: 'İstifadəçi girişinin təmin edilməsi', description: 'Bütün sistemlərə bütün növ istifadəçilərin giriş hüquqlarını təyin etmək üçün rəsmi proses həyata keçirilməlidir.' },
  { code: 'A.9.2.3',  name: 'İmtiyazlı girişin idarə edilməsi', description: 'İmtiyazlı giriş hüquqlarının bölüşdürülməsi və istifadəsi məhdudlaşdırılmalı və nəzarət edilməlidir.' },
  { code: 'A.9.2.4',  name: 'İstifadəçilərin məxfi autentifikasiya məlumatlarının idarə edilməsi', description: 'Məxfi autentifikasiya məlumatlarının bölüşdürülməsinə rəsmi idarəetmə prosesi vasitəsilə nəzarət edilməlidir.' },
  { code: 'A.9.2.5',  name: 'İstifadəçilərin giriş hüquqlarının nəzərdən keçirilməsi', description: 'Aktiv sahibləri istifadəçilərin giriş hüquqlarını müntəzəm şəkildə nəzərdən keçirməlidirlər.' },
  { code: 'A.9.2.6',  name: 'Giriş hüquqlarının çıxarılması və ya tənzimlənməsi', description: 'İşçilərin məlumat emalı vasitələrinə giriş hüquqları əmək münasibətlərinə xitam verildikdə dayandırılır.' },
  { code: 'A.9.3.1',  name: 'Məxfi autentifikasiya məlumatlarından istifadə', description: 'İstifadəçilərdən məxfi autentifikasiya məlumatlarından istifadə ilə bağlı qəbul edilmiş təcrübələrə riayət etmələri tələb olunmalıdır.' },
  { code: 'A.9.4.1',  name: 'Məlumata çıxışın məhdudlaşdırılması', description: 'İnformasiyaya giriş girişə nəzarət siyasətinə uyğun olaraq məhdudlaşdırılmalıdır.' },
  { code: 'A.9.4.2',  name: 'Təhlükəsiz giriş prosedurları', description: 'Girişə nəzarət siyasəti tələb edərsə, sistemlərə giriş təhlükəsiz giriş prosedurundan istifadə edilməklə idarə olunmalıdır.' },
  { code: 'A.9.4.3',  name: 'Parol idarəetmə sistemi', description: 'Parol idarəetmə sistemləri interaktiv olmalı və keyfiyyətli parolları təmin etməlidir.' },
  { code: 'A.9.4.4',  name: 'İmtiyazlı yardımçı proqramların istifadəsi', description: 'Sistem nəzarəti vasitələrini üstələyə bilən yardımçı proqramların istifadəsi məhdudlaşdırılmalıdır.' },
  { code: 'A.9.4.5',  name: 'Proqramın mənbə koduna giriş nəzarəti', description: 'Proqramın mənbə koduna giriş məhdudlaşdırılmalıdır.' },
  { code: 'A.10.1.1', name: 'Kriptoqrafik nəzarət vasitələrinin istifadəsi ilə bağlı siyasət', description: 'İnformasiyanın mühafizəsi üçün kriptoqrafik idarəetmə vasitələrinin istifadəsinə dair siyasət hazırlanmalı və həyata keçirilməlidir.' },
  { code: 'A.10.1.2', name: 'Açarların idarə edilməsi', description: 'Kriptoqrafik açarların istifadəsi, mühafizəsi və istifadə müddəti ilə bağlı siyasət həyat dövrü ərzində hazırlanmalıdır.' },
  { code: 'A.11.1.1', name: 'Fiziki təhlükəsizlik perimetri', description: 'Təhlükəsizlik perimetrləri məxfi məlumat və məlumat emal vasitələri olan əraziləri mühafizə etmək üçün müəyyən edilməlidir.' },
  { code: 'A.11.1.2', name: 'Fiziki giriş nəzarəti', description: 'Təhlükəsiz ərazilərə yalnız icazə verilmiş personalın girişini təmin etmək üçün müvafiq giriş nəzarəti vasitələri olmalıdır.' },
  { code: 'A.11.1.3', name: 'Ofislərin, otaqların və obyektlərin mühafizəsi', description: 'Ofislərin, otaqların və obyektlərin fiziki mühafizəsi layihələndirilməli və tətbiq edilməlidir.' },
  { code: 'A.11.1.4', name: 'Xarici və ətraf mühit təhdidlərindən qorunma', description: 'Yanğın, daşqın, zəlzələ, partlayış və digər fəlakətlərə qarşı fiziki mühafizə layihələndirilməli və tətbiq edilməlidir.' },
  { code: 'A.11.1.5', name: 'Təhlükəsiz zonalarda işləmək', description: 'Təhlükəsiz zonalarda işləmək üçün prosedurlar işlənib hazırlanmalı və tətbiq edilməlidir.' },
  { code: 'A.11.1.6', name: 'Çatdırılma və yükləmə sahələri', description: 'Giriş nöqtələri nəzarət edilməli və mümkünsə icazəsiz girişin qarşısını almaq üçün məlumat emalı vasitələrindən təcrid edilməlidir.' },
  { code: 'A.11.2.1', name: 'Avadanlıqların yerləşdirilməsi və mühafizəsi', description: 'Avadanlıqlar ətraf mühitin təhdidlərini azaltmaq və icazəsiz girişin imkanlarını azaltmaq üçün yerləşdirilməlidir.' },
  { code: 'A.11.2.2', name: 'Dəstəkləyici kommunikasiyalar', description: 'Avadanlıqlar elektrik enerjisinin kəsilməsi və kommunikasiya xidmətlərinin pozulmalarından qorunmalıdır.' },
  { code: 'A.11.2.3', name: 'Kabel təhlükəsizliyi', description: 'Elektrik enerji ötürücüsü və ya telekommunikasiya kabeli eşidilmə, müdaxilə və zədələnmədən qorunmalıdır.' },
  { code: 'A.11.2.4', name: 'Avadanlıqlara texniki xidmət', description: 'Avadanlıqların davamlı mövcudluğunu və bütövlüyünü təmin etmək üçün lazımi texniki xidmət göstərilməlidir.' },
  { code: 'A.11.2.5', name: 'Aktivlərin çıxarılması', description: 'Avadanlıq, məlumat və proqram təminatı əvvəlcədən icazə alınmadan ərazidən çıxarılmamalıdır.' },
  { code: 'A.11.2.6', name: 'Sahədənkənar avadanlığın və aktivlərin təhlükəsizliyi', description: 'Sahənin xaricindəki aktivlərə müxtəlif xətərlər nəzərə alınmaqla təhlükəsizlik tədbirləri tətbiq edilməlidir.' },
  { code: 'A.11.2.7', name: 'İstifadəyə yararsız avadanlıqların utilizasiyası', description: 'Saxlama mediasını ehtiva edən avadanlıqlar istifadəyə yararsız hala gətirilmədən əvvəl yoxlanılmalıdır.' },
  { code: 'A.11.2.8', name: 'Nəzarətsiz istifadəçi avadanlıqları', description: 'Bütün istifadəçilər avadanlıqların lazımi müdafiəsini təmin etməlidirlər.' },
  { code: 'A.11.2.9', name: 'Təmiz iş masası və təmiz ekran siyasəti', description: 'Kağızlar, çıxarıla bilən saxlama mediası üçün təmiz iş masası siyasəti qəbul edilməlidir.' },
  { code: 'A.12.1.1', name: 'Sənədləşdirilmiş əməliyyat prosedurları', description: 'Əməliyyat prosedurları sənədləşdirilməli və ehtiyac duyulan bütün istifadəçilər üçün əlçatan edilməlidir.' },
  { code: 'A.12.1.2', name: 'Dəyişikliklərin idarə edilməsi', description: 'Təşkilata, iş proseslərinə, məlumat emalı vasitələrinə və sistemlərə edilən dəyişikliklər nəzarət edilməlidir.' },
  { code: 'A.12.1.3', name: 'Tutum idarəetməsi', description: 'Tələb olunan sistem performansını təmin etmək üçün resursların istifadəsi izlənilməli və gələcək tutum tələbləri proqnozlaşdırılmalıdır.' },
  { code: 'A.12.1.4', name: 'İnkişaf, test və istismar mühitlərinin ayrılması', description: 'İnkişaf, test və istismar mühitlərinin ayrılması tətbiq edilməlidir.' },
  { code: 'A.12.2.1', name: 'Zərərli proqramdan qorunma', description: 'Zərərli proqramdan qorunma vasitəsilə aşkarlama, qarşısının alınması və bərpadan istifadəyə dair idarəetmə vasitələri həyata keçirilməlidir.' },
  { code: 'A.12.3.1', name: 'Məlumatların ehtiyat nüsxəsinin çıxarılması', description: 'Məlumatların ehtiyat nüsxələri razılaşdırılmış siyasətə uyğun olaraq mütəmadi olaraq çıxarılmalı və sınaqdan keçirilməlidir.' },
  { code: 'A.12.4.1', name: 'Hadisə qeydinin aparılması', description: 'İstifadəçi fəaliyyətlərini, nasazlıqları və informasiya təhlükəsizliyi hadisələrini qeydə alan qeydlər yaradılmalı və nəzərdən keçirilməlidir.' },
  { code: 'A.12.4.2', name: 'Qeyd məlumatlarının mühafizəsi', description: 'Qeyd imkanları icazəsiz giriş imkanlarına qarşı mühafizə olunmalıdır.' },
  { code: 'A.12.4.3', name: 'Administrator və operator qeydləri', description: 'Sistem administratoru fəaliyyəti qeyd edilməli, mühafizə olunmalı və nəzərdən keçirilməlidir.' },
  { code: 'A.12.4.4', name: 'Saatların sinxronizasiyası', description: 'Bütün məlumat emalı sistemlərinin saatları yetkiləndirilmiş vaxt mənbəyindən istifadə edərək sinxronizasiya edilməlidir.' },
  { code: 'A.12.5.1', name: 'Əməliyyat sistemlərindəki proqram təminatının quraşdırılması', description: 'İstismar sistemlərindəki proqram təminatının quraşdırılmasını idarə etmək üçün prosedurlar həyata keçirilməlidir.' },
  { code: 'A.12.6.1', name: 'Texniki boşluqların idarə edilməsi', description: 'İstifadə olunan informasiya sistemlərinin texniki boşluqları haqqında vaxtında məlumat əldə edilməli və müvafiq tədbirlər görülməlidir.' },
  { code: 'A.12.6.2', name: 'Proqram təminatının quraşdırılmasına məhdudiyyətlər', description: 'Proqram təminatının quraşdırılmasına münasibətdə istifadəçilər tərəfindən qaydalar müəyyən edilməli və həyata keçirilməlidir.' },
  { code: 'A.12.7.1', name: 'İnformasiya sistemlərinin auditi üçün nəzarət vasitələri', description: 'Audit tələbləri əməliyyat proseslərinin pozulmasını minimuma endirmək üçün diqqətlə planlaşdırılmalıdır.' },
  { code: 'A.13.1.1', name: 'Şəbəkənin idarə edilməsi', description: 'Şəbəkələr sistemlər daxilindəki məlumatı qorumaq üçün idarə edilməli və nəzarət edilməlidir.' },
  { code: 'A.13.1.2', name: 'Şəbəkə xidmətlərinin təhlükəsizliyi', description: 'Bütün şəbəkə xidmətlərinin təhlükəsizlik mexanizmləri şəbəkə xidmətləri müqavilələrinə daxil edilməlidir.' },
  { code: 'A.13.1.3', name: 'Şəbəkələrdə ayrılma', description: 'İnformasiya xidmətləri qrupları, istifadəçilər və informasiya sistemləri şəbəkələr üzrə ayrılmalıdır.' },
  { code: 'A.13.2.1', name: 'Məlumat ötürmə siyasəti və prosedurları', description: 'Məlumatların ötürülməsini təmin etmək üçün rəsmi ötürmə siyasətləri və idarəetmə vasitələri tətbiq edilməlidir.' },
  { code: 'A.13.2.2', name: 'Məlumat ötürülməsi üzrə müqavilələr', description: 'Müqavilələr təşkilat və üçüncü tərəflər arasında biznes məlumatlarının təhlükəsiz ötürülməsini əhatə etməlidir.' },
  { code: 'A.13.2.3', name: 'Elektron mesajlaşma', description: 'Elektron mesajlaşma ilə bağlı məlumatlar müvafiq qaydada qorunmalıdır.' },
  { code: 'A.13.2.4', name: 'Məxfilik müqavilələri', description: 'Məxfilik müqavilələrinə dair tələblər müəyyən edilməli, mütəmadi olaraq nəzərdən keçirilməlidir.' },
  { code: 'A.14.1.1', name: 'İnformasiya təhlükəsizliyi tələblərinin təhlili', description: 'İnformasiya təhlükəsizliyi ilə bağlı tələblər yeni informasiya sistemlərinin tələblərinə daxil edilməlidir.' },
  { code: 'A.14.1.2', name: 'Ümumistifadəli şəbəkələrdə tətbiq xidmətlərinin təhlükəsizliyi', description: 'Ümumistifadəli şəbəkələr üzərindən ötürülən tətbiq xidmətləri ilə bağlı məlumatlar fırıldaqçılıq və icazəsiz açıqlamadan qorunmalıdır.' },
  { code: 'A.14.1.3', name: 'Tətbiq xidmətləri əməliyyatlarının qorunması', description: 'Tətbiq xidməti əməliyyatları ilə bağlı məlumatların icazəsiz dəyişdirilməsinin qarşısını almaq üçün tədbirlər görülməlidir.' },
  { code: 'A.14.2.1', name: 'Təhlükəsiz inkişaf siyasəti', description: 'Proqram təminatının və sistemlərin işlənib hazırlanması qaydaları müəyyən edilməli və həyata keçirilməlidir.' },
  { code: 'A.14.2.2', name: 'Sistemdəki dəyişikliklərə nəzarət prosedurları', description: 'İnkişafın həyat dövrü ərzində sistemlərə edilən dəyişikliklərə rəsmi dəyişikliklərin idarə edilməsi prosedurlarından istifadə etməklə nəzarət edilməlidir.' },
  { code: 'A.14.2.3', name: 'Əməliyyat platformasını dəyişdirdikdən sonra tətbiqlərin texniki təhlili', description: 'Əməliyyat platformaları dəyişdikdə, əhəmiyyətli biznes tətbiqləri nəzərdən keçirilməli və test olunmalıdır.' },
  { code: 'A.14.2.4', name: 'Proqram paketlərinə dəyişikliklərin edilməsinə məhdudiyyətlər', description: 'Zəruri dəyişikliklərlə məhdudlaşmaqla, proqram paketlərinə düzəlişlər etmək tövsiyə edilmir.' },
  { code: 'A.14.2.5', name: 'Sistem mühəndisliyi prinsiplərinin təmin edilməsi', description: 'Mühəndislik təhlükəsizliyi sistemlərinin prinsipləri qurulmalı, sənədləşdirilməli və tətbiq edilməlidir.' },
  { code: 'A.14.2.6', name: 'Təhlükəsiz işləmə mühiti', description: 'Sistem inkişafı üçün təhlükəsiz inkişaf mühitləri yaradılmalı və qorunmalıdır.' },
  { code: 'A.14.2.7', name: 'Autsorsing işləmə', description: 'Təşkilat autsorsing sisteminin işlənib hazırlanması fəaliyyətinə nəzarət etməli və monitorinqini aparmalıdır.' },
  { code: 'A.14.2.8', name: 'Sistem təhlükəsizlik testi', description: 'İşləyib hazırlama zamanı təhlükəsizlik funksionallığının testi aparılmalıdır.' },
  { code: 'A.14.2.9', name: 'Sistemin qəbulu testi', description: 'Yeni informasiya sistemləri üçün test proqramlarının qəbulu meyarları müəyyən edilməlidir.' },
  { code: 'A.14.3.1', name: 'Test məlumatlarının qorunması', description: 'Test məlumatları diqqətlə seçilməli, qorunmalı və nəzarət edilməlidir.' },
  { code: 'A.15.1.1', name: 'Təchizatçı münasibətləri üçün informasiya təhlükəsizliyi siyasəti', description: 'Təchizatçının təşkilatın aktivlərinə çıxışı ilə bağlı risklərin azaldılması üçün tələblər razılaşdırılmalıdır.' },
  { code: 'A.15.1.2', name: 'Təchizatçılarla müqavilələr çərçivəsində təhlükəsizliyin təmin edilməsi', description: 'Bütün müvafiq informasiya təhlükəsizliyi tələbləri hər bir müvafiq təchizatçı ilə razılaşdırılmalıdır.' },
  { code: 'A.15.1.3', name: 'İnformasiya və kommunikasiya texnologiyalarının təchizat zənciri', description: 'Müqavilələr İKT xidmətləri və məhsulun tədarük zənciri ilə bağlı risklərin aradan qaldırılması tələblərini əhatə etməlidir.' },
  { code: 'A.15.2.1', name: 'Təchizatçı xidmətlərinin monitorinqi və təhlili', description: 'Təşkilatlar mütəmadi olaraq təchizatçı tərəfindən xidmət göstərilməsinə nəzarət etməli və auditini aparmalıdır.' },
  { code: 'A.15.2.2', name: 'Təchizatçı xidmətlərində dəyişikliklərin idarə edilməsi', description: 'Təchizatçılar tərəfindən xidmətlərə edilən dəyişikliklər risklərin yenidən qiymətləndirilməsi nəzərə alınmaqla idarə edilməlidir.' },
  { code: 'A.16.1.1', name: 'Məsuliyyətlər və prosedurlar', description: 'İnformasiya təhlükəsizliyi ilə bağlı insidentlərə operativ cavab verilməsini təmin etmək üçün prosedurlar müəyyən edilməlidir.' },
  { code: 'A.16.1.2', name: 'İnformasiya təhlükəsizliyi insidentləri barədə məlumat verilməsi', description: 'İnformasiya təhlükəsizliyi hadisələri müvafiq idarəetmə kanalları vasitəsilə mümkün olan ən qısa zamanda bildirilməlidir.' },
  { code: 'A.16.1.3', name: 'İnformasiya təhlükəsizliyi ilə bağlı zəifliklər barədə məlumat verilməsi', description: 'İşçilər müşahidə etdikləri informasiya təhlükəsizliyi zəifliklərini qeyd etməli və bu barədə məlumat verməlidirlər.' },
  { code: 'A.16.1.4', name: 'İnformasiya təhlükəsizliyi insidentlərinin qiymətləndirilməsi', description: 'İnformasiya təhlükəsizliyi hadisələri qiymətləndirilməli və insidentlər kimi təsnif edilib-edilməməsi barədə qərar qəbul edilməlidir.' },
  { code: 'A.16.1.5', name: 'İnformasiya təhlükəsizliyi insidentlərinə cavab verilməsi', description: 'İnformasiya təhlükəsizliyi insidentlərinə sənədləşdirilmiş prosedurlara uyğun olaraq cavab verilməlidir.' },
  { code: 'A.16.1.6', name: 'İnformasiya təhlükəsizliyi insidentlərindən öyrənmə', description: 'Əldə edilən biliklər gələcək hadisələrin ehtimalını azaltmaq məqsədilə istifadə edilməlidir.' },
  { code: 'A.16.1.7', name: 'Dəlillərin toplanması', description: 'Dəlil kimi verilə biləcək məlumatların toplanması, əldə edilməsi və saxlanılması prosedurları müəyyən edilməlidir.' },
  { code: 'A.17.1.1', name: 'İnformasiya təhlükəsizliyinin davamlılığının planlaşdırılması', description: 'Təşkilat informasiya təhlükəsizliyinə dair tələblərini müəyyən etməlidir.' },
  { code: 'A.17.1.2', name: 'İnformasiya təhlükəsizliyinin davamlılığının həyata keçirilməsi', description: 'Əlverişsiz vəziyyət zamanı informasiya təhlükəsizliyinin davamlılığını təmin etmək üçün proseslər yaradılmalıdır.' },
  { code: 'A.17.1.3', name: 'İnformasiya təhlükəsizliyinin davamlılığını yoxlamaq', description: 'Davamlılıq nəzarət vasitələrinin etibarlı olmasını təmin etmək üçün müntəzəm olaraq yoxlanılmalıdır.' },
  { code: 'A.17.2.1', name: 'İnformasiya emalı vasitələrinin mövcudluğu', description: 'İnformasiya emal vasitələri mövcudluq tələblərinə cavab verəcək şəkildə həyata keçirilməlidir.' },
  { code: 'A.18.1.1', name: 'Tətbiq olunan qanunvericiliyin və müqavilə tələblərinin müəyyən edilməsi', description: 'Bütün müvafiq qanunvericilik, tənzimləyici, müqavilə tələbləri hər bir informasiya sistemi üçün aydın şəkildə müəyyən edilməlidir.' },
  { code: 'A.18.1.2', name: 'Əqli mülkiyyət hüquqları', description: 'Əqli mülkiyyət hüquqları ilə bağlı hüquqi tələblərə əməl olunmasını təmin etmək üçün müvafiq prosedurlar həyata keçirilməlidir.' },
  { code: 'A.18.1.3', name: 'Qeydlərin mühafizəsi', description: 'Qeydlər hüquqi, normativ, müqavilə və biznes tələblərinə uyğun olaraq qorunmalıdır.' },
  { code: 'A.18.1.4', name: 'Şəxsi məlumatların məxfiliyi və qorunması', description: 'Şəxsi məlumatların məxfiliyi müvafiq qanun və qaydaların tələblərinə uyğun olaraq təmin edilməlidir.' },
  { code: 'A.18.1.5', name: 'Kriptoqrafik nəzarətin tənzimlənməsi', description: 'Kriptoqrafik idarəetmə vasitələri bütün müvafiq müqavilələrə və qanunvericiliyə uyğun olaraq istifadə edilməlidir.' },
  { code: 'A.18.2.1', name: 'İnformasiya təhlükəsizliyinin müstəqil nəzərdən keçirilməsi', description: 'Təşkilatın informasiya təhlükəsizliyinin idarə edilməsinə yanaşması planlaşdırılan intervallarda müstəqil şəkildə nəzərdən keçirilməlidir.' },
  { code: 'A.18.2.2', name: 'Təhlükəsizlik siyasətləri və standartlarına uyğunluq', description: 'Menecerlər mütəmadi olaraq öz məsuliyyət dairələri daxilində informasiyanın işlənməsinin müvafiq təhlükəsizlik siyasətlərinə uyğunluğunu yoxlamalıdırlar.' },
  { code: 'A.18.2.3', name: 'Texniki şərtlərə uyğunluğun yoxlanılması', description: 'İnformasiya sistemlərinin informasiya təhlükəsizliyi siyasətlərına uyğunluğu mütəmadi olaraq yoxlanılmalıdır.' },
];
