export const isoDataEn = [
  { code: 'A.5.1.1',  name: 'Information security policy', description: 'A set of policies for information security shall be defined, approved by management, published and communicated to employees and relevant external parties.' },
  { code: 'A.5.1.2',  name: 'Review of the policies for information security', description: 'The policies for information security shall be reviewed at planned intervals or if significant changes occur to ensure their continuing suitability, adequacy and effectiveness.' },
  { code: 'A.6.1.1',  name: 'Information security roles and responsibilities', description: 'All information security responsibilities shall be defined and allocated.' },
  { code: 'A.6.1.2',  name: 'Segregation of duties', description: 'Conflicting duties and areas of responsibility shall be segregated to reduce opportunities for unauthorized or unintentional modification or misuse of the organization\'s assets.' },
  { code: 'A.6.1.3',  name: 'Contact with authorities', description: 'Appropriate contacts with relevant authorities shall be maintained.' },
  { code: 'A.6.1.4',  name: 'Contact with special interest groups', description: 'Appropriate contacts with special interest groups or other specialist security forums and professional associations shall be maintained.' },
  { code: 'A.6.1.5',  name: 'Information security in project management', description: 'Information security shall be addressed in project management, regardless of the type of the project.' },
  { code: 'A.6.2.1',  name: 'Mobile device policy', description: 'A policy and supporting security measures shall be adopted to manage the risks introduced by using mobile devices.' },
  { code: 'A.6.2.2',  name: 'Teleworking', description: 'A policy and supporting security measures shall be implemented to protect information accessed, processed or stored at teleworking sites.' },
  { code: 'A.7.1.1',  name: 'Screening', description: 'Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics.' },
  { code: 'A.7.1.2',  name: 'Terms and conditions of employment', description: 'The contractual agreements with employees and contractors shall state their and the organization\'s responsibilities for information security.' },
  { code: 'A.7.2.1',  name: 'Management responsibilities', description: 'Management shall require all employees and contractors to apply information security in accordance with the established policies of the organization.' },
  { code: 'A.7.2.2',  name: 'Information labeling and handling', description: 'Procedures for information labeling and handling shall be developed in accordance with the classification scheme adopted by the organization.' },
  { code: 'A.7.2.3',  name: 'Disciplinary process', description: 'There shall be a formal disciplinary process to take action against employees who have committed an information security breach.' },
  { code: 'A.7.3.1',  name: 'Termination or change of employment responsibilities', description: 'Information security responsibilities that remain valid after termination shall be communicated to the employee and enforced.' },
  { code: 'A.8.1.1',  name: 'Inventory of assets', description: 'Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be maintained.' },
  { code: 'A.8.1.2',  name: 'Ownership of assets', description: 'Assets maintained in the inventory shall be owned.' },
  { code: 'A.8.1.3',  name: 'Acceptable use of assets', description: 'Rules for the acceptable use of information and of assets shall be identified, documented and implemented.' },
  { code: 'A.8.1.4',  name: 'Return of assets', description: 'All employees shall return all of the organizational assets in their possession upon termination of their employment.' },
  { code: 'A.8.2.1',  name: 'Classification of information', description: 'Information shall be classified in terms of legal requirements, value, and criticality.' },
  { code: 'A.8.2.2',  name: 'Labeling of information', description: 'Appropriate procedures for information labeling shall be implemented in accordance with the classification scheme adopted.' },
  { code: 'A.8.2.3',  name: 'Management of assets', description: 'Procedures for managing assets shall be in accordance with the adopted information classification scheme.' },
  { code: 'A.8.3.1',  name: 'Management of removable media', description: 'Procedures shall be implemented for the management of removable media.' },
  { code: 'A.8.3.2',  name: 'Disposal of media', description: 'Media shall be disposed of securely when no longer required, using formal procedures.' },
  { code: 'A.8.3.3',  name: 'Physical media transfer', description: 'Media containing information shall be protected against unauthorized access and damage during transport.' },
  { code: 'A.9.1.1',  name: 'Access control policy', description: 'An access control policy shall be established and reviewed based on business and information security requirements.' },
  { code: 'A.9.1.2',  name: 'Access to networks and network services', description: 'Users shall only be provided with access to the network and network services that they have been specifically authorized to use.' },
  { code: 'A.9.2.1',  name: 'User registration and de-registration', description: 'A formal user registration process shall be implemented to enable assignment of access rights.' },
  { code: 'A.9.2.2',  name: 'User access provisioning', description: 'A formal process shall be implemented to assign access rights for all user types to all systems.' },
  { code: 'A.9.2.3',  name: 'Management of privileged access rights', description: 'The allocation and use of privileged access rights shall be restricted and controlled.' },
  { code: 'A.9.2.4',  name: 'Management of secret authentication information of users', description: 'The allocation of secret authentication information shall be controlled through a formal management process.' },
  { code: 'A.9.2.5',  name: 'Review of user access rights', description: 'Asset owners shall review users\' access rights at regular intervals.' },
  { code: 'A.9.2.6',  name: 'Removal or adjustment of access rights', description: 'The access rights of employees to information processing facilities shall be terminated upon termination of employment.' },
  { code: 'A.9.3.1',  name: 'Use of secret authentication information', description: 'Users shall be required to follow the accepted practices in the use of secret authentication information.' },
  { code: 'A.9.4.1',  name: 'Information access restriction', description: 'Access to information shall be restricted in accordance with the access control policy.' },
  { code: 'A.9.4.2',  name: 'Secure log-on procedures', description: 'Where required by the access control policy, access to systems shall be controlled by a secure log-on procedure.' },
  { code: 'A.9.4.3',  name: 'Password management system', description: 'Password management systems shall be interactive and ensure quality passwords.' },
  { code: 'A.9.4.4',  name: 'Use of privileged utility programs', description: 'The use of utility programs that might be capable of overriding system controls shall be restricted.' },
  { code: 'A.9.4.5',  name: 'Access control to program source code', description: 'Access to program source code shall be restricted.' },
  { code: 'A.10.1.1', name: 'Policy on the use of cryptographic controls', description: 'A policy on the use of cryptographic controls for protection of information shall be developed and implemented.' },
  { code: 'A.10.1.2', name: 'Key management', description: 'A policy on the use, protection and lifetime of cryptographic keys shall be developed through their life cycle.' },
  { code: 'A.11.1.1', name: 'Physical security perimeter', description: 'Security perimeters shall be defined to protect areas that contain confidential information and information processing facilities.' },
  { code: 'A.11.1.2', name: 'Physical entry controls', description: 'Secure areas shall be protected by appropriate entry controls to ensure that only authorized personnel are allowed access.' },
  { code: 'A.11.1.3', name: 'Securing offices, rooms and facilities', description: 'Physical security for offices, rooms and facilities shall be designed and applied.' },
  { code: 'A.11.1.4', name: 'Protecting against external and environmental threats', description: 'Physical protection against fire, flood, earthquake, explosion and other disasters shall be designed and applied.' },
  { code: 'A.11.1.5', name: 'Working in secure areas', description: 'Procedures for working in secure areas shall be developed and applied.' },
  { code: 'A.11.1.6', name: 'Delivery and loading areas', description: 'Access points shall be controlled and, if possible, isolated from information processing facilities to avoid unauthorized access.' },
  { code: 'A.11.2.1', name: 'Equipment siting and protection', description: 'Equipment shall be sited to reduce the risks from environmental threats and opportunities for unauthorized access.' },
  { code: 'A.11.2.2', name: 'Supporting utilities', description: 'Equipment shall be protected from power failures and disruptions caused by failures in supporting utilities.' },
  { code: 'A.11.2.3', name: 'Cabling security', description: 'Power and telecommunications cabling shall be protected from interception, interference and damage.' },
  { code: 'A.11.2.4', name: 'Equipment maintenance', description: 'Equipment shall be correctly maintained to ensure its continued availability and integrity.' },
  { code: 'A.11.2.5', name: 'Removal of assets', description: 'Equipment, information or software shall not be taken off-site without prior authorization.' },
  { code: 'A.11.2.6', name: 'Security of off-site equipment and assets', description: 'Security measures shall be applied to off-site assets, taking into account the different risks.' },
  { code: 'A.11.2.7', name: 'Secure disposal or re-use of equipment', description: 'Equipment containing storage media shall be verified prior to being made unusable.' },
  { code: 'A.11.2.8', name: 'Unattended user equipment', description: 'All users shall ensure that unattended equipment has appropriate protection.' },
  { code: 'A.11.2.9', name: 'Clear desk and clear screen policy', description: 'A clear desk policy for papers and removable storage media shall be adopted.' },
  { code: 'A.12.1.1', name: 'Documented operating procedures', description: 'Operating procedures shall be documented and made available to all users who need them.' },
  { code: 'A.12.1.2', name: 'Change management', description: 'Changes to the organization, business processes, information processing facilities and systems shall be controlled.' },
  { code: 'A.12.1.3', name: 'Capacity management', description: 'The use of resources shall be monitored and future capacity requirements projected to ensure the required system performance.' },
  { code: 'A.12.1.4', name: 'Separation of development, testing and operational environments', description: 'Separation of development, testing and operational environments shall be applied.' },
  { code: 'A.12.2.1', name: 'Controls against malware', description: 'Detection, prevention and recovery controls to protect against malware shall be implemented.' },
  { code: 'A.12.3.1', name: 'Information backup', description: 'Backup copies of information shall be taken and tested regularly in accordance with an agreed policy.' },
  { code: 'A.12.4.1', name: 'Event logging', description: 'Logs recording user activities, exceptions and information security events shall be produced and reviewed.' },
  { code: 'A.12.4.2', name: 'Protection of log information', description: 'Logging facilities shall be protected against unauthorized access opportunities.' },
  { code: 'A.12.4.3', name: 'Administrator and operator logs', description: 'System administrator activities shall be logged, protected and reviewed.' },
  { code: 'A.12.4.4', name: 'Clock synchronization', description: 'The clocks of all information processing systems shall be synchronized using an authorized time source.' },
  { code: 'A.12.5.1', name: 'Installation of software on operational systems', description: 'Procedures shall be implemented to control the installation of software on operational systems.' },
  { code: 'A.12.6.1', name: 'Management of technical vulnerabilities', description: 'Timely information about technical vulnerabilities of information systems being used shall be obtained and appropriate measures taken.' },
  { code: 'A.12.6.2', name: 'Restrictions on software installation', description: 'Rules governing the installation of software by users shall be defined and implemented.' },
  { code: 'A.12.7.1', name: 'Information systems audit controls', description: 'Audit requirements shall be carefully planned to minimize the disruption of operational processes.' },
  { code: 'A.13.1.1', name: 'Network controls', description: 'Networks shall be managed and controlled to protect information within systems.' },
  { code: 'A.13.1.2', name: 'Security of network services', description: 'Security mechanisms of all network services shall be included in network services agreements.' },
  { code: 'A.13.1.3', name: 'Segregation in networks', description: 'Groups of information services, users and information systems shall be segregated on networks.' },
  { code: 'A.13.2.1', name: 'Information transfer policies and procedures', description: 'Formal transfer policies and controls shall be implemented to protect the transfer of information.' },
  { code: 'A.13.2.2', name: 'Agreements on information transfer', description: 'Agreements shall address the secure transfer of business information between the organization and third parties.' },
  { code: 'A.13.2.3', name: 'Electronic messaging', description: 'Information involved in electronic messaging shall be appropriately protected.' },
  { code: 'A.13.2.4', name: 'Confidentiality agreements', description: 'Requirements for confidentiality agreements shall be identified and regularly reviewed.' },
  { code: 'A.14.1.1', name: 'Information security requirements analysis', description: 'Information security related requirements shall be included in the requirements for new information systems.' },
  { code: 'A.14.1.2', name: 'Securing application services on public networks', description: 'Information involved in application services passing over public networks shall be protected from fraudulent activity and unauthorized disclosure.' },
  { code: 'A.14.1.3', name: 'Protecting application services transactions', description: 'Information involved in application service transactions shall be protected to prevent unauthorized modification.' },
  { code: 'A.14.2.1', name: 'Secure development policy', description: 'Rules for the development of software and systems shall be established and implemented.' },
  { code: 'A.14.2.2', name: 'System change control procedures', description: 'Changes to systems within the development life cycle shall be controlled by the use of formal change control procedures.' },
  { code: 'A.14.2.3', name: 'Technical review of applications after operating platform changes', description: 'When operating platforms are changed, business critical applications shall be reviewed and tested.' },
  { code: 'A.14.2.4', name: 'Restrictions on modifications to software packages', description: 'Modifications to software packages shall be discouraged, being limited to necessary changes.' },
  { code: 'A.14.2.5', name: 'Secure system engineering principles', description: 'Principles for engineering secure systems shall be established, documented and applied.' },
  { code: 'A.14.2.6', name: 'Secure development environment', description: 'Secure development environments for system development shall be established and protected.' },
  { code: 'A.14.2.7', name: 'Outsourced development', description: 'The organization shall supervise and monitor the activity of outsourced system development.' },
  { code: 'A.14.2.8', name: 'System security testing', description: 'Testing of security functionality shall be carried out during development.' },
  { code: 'A.14.2.9', name: 'System acceptance testing', description: 'Acceptance testing criteria shall be defined for new information systems.' },
  { code: 'A.14.3.1', name: 'Protection of test data', description: 'Test data shall be selected carefully, protected and controlled.' },
  { code: 'A.15.1.1', name: 'Information security policy for supplier relationships', description: 'Requirements for mitigating the risks associated with supplier\'s access to the organization\'s assets shall be agreed.' },
  { code: 'A.15.1.2', name: 'Addressing security within supplier agreements', description: 'All relevant information security requirements shall be agreed with each relevant supplier.' },
  { code: 'A.15.1.3', name: 'Information and communication technology supply chain', description: 'Agreements shall include requirements to address information security risks associated with ICT services and product supply chain.' },
  { code: 'A.15.2.1', name: 'Monitoring and review of supplier services', description: 'Organizations shall regularly monitor and audit supplier service delivery.' },
  { code: 'A.15.2.2', name: 'Managing changes to supplier services', description: 'Changes to the provision of services by suppliers shall be managed, taking account of the reassessment of risks.' },
  { code: 'A.16.1.1', name: 'Responsibilities and procedures', description: 'Procedures shall be established to ensure a quick response to information security incidents.' },
  { code: 'A.16.1.2', name: 'Reporting information security events', description: 'Information security events shall be reported through appropriate management channels as quickly as possible.' },
  { code: 'A.16.1.3', name: 'Reporting information security weaknesses', description: 'Employees shall note and report any observed information security weaknesses.' },
  { code: 'A.16.1.4', name: 'Assessment of information security events', description: 'Information security events shall be assessed and it shall be decided if they are to be classified as incidents.' },
  { code: 'A.16.1.5', name: 'Response to information security incidents', description: 'Information security incidents shall be responded to in accordance with the documented procedures.' },
  { code: 'A.16.1.6', name: 'Learning from information security incidents', description: 'Knowledge gained shall be used to reduce the likelihood of future events.' },
  { code: 'A.16.1.7', name: 'Collection of evidence', description: 'Procedures shall be defined for the collection, acquisition and preservation of information that can be presented as evidence.' },
  { code: 'A.17.1.1', name: 'Planning information security continuity', description: 'The organization shall determine its requirements for information security.' },
  { code: 'A.17.1.2', name: 'Implementing information security continuity', description: 'Processes shall be established to ensure information security continuity during an adverse situation.' },
  { code: 'A.17.1.3', name: 'Verify information security continuity', description: 'Continuity controls shall be verified regularly to ensure they are valid.' },
  { code: 'A.17.2.1', name: 'Availability of information processing facilities', description: 'Information processing facilities shall be implemented in a way that meets availability requirements.' },
  { code: 'A.18.1.1', name: 'Identification of applicable legislation and contractual requirements', description: 'All relevant legislative, regulatory, and contractual requirements shall be explicitly defined for each information system.' },
  { code: 'A.18.1.2', name: 'Intellectual property rights', description: 'Appropriate procedures shall be implemented to ensure compliance with legislative requirements regarding intellectual property rights.' },
  { code: 'A.18.1.3', name: 'Protection of records', description: 'Records shall be protected in accordance with legislative, regulatory, contractual and business requirements.' },
  { code: 'A.18.1.4', name: 'Privacy and protection of personal information', description: 'Privacy of personal information shall be ensured in accordance with the requirements of relevant laws and regulations.' },
  { code: 'A.18.1.5', name: 'Regulation of cryptographic controls', description: 'Cryptographic controls shall be used in compliance with all relevant agreements and legislation.' },
  { code: 'A.18.2.1', name: 'Independent review of information security', description: 'The organization\'s approach to managing information security shall be independently reviewed at planned intervals.' },
  { code: 'A.18.2.2', name: 'Compliance with security policies and standards', description: 'Managers shall regularly review the compliance of information processing within their area of responsibility with the appropriate security policies.' },
  { code: 'A.18.2.3', name: 'Technical compliance review', description: 'Information systems shall be regularly reviewed for compliance with information security policies.' }
];