export const nistData = [
  { code: 'GV.OC-01', name: 'Təşkilati missiya başa düşülür və kibertəhlükəsizlik risklərinin idarə edilməsini məlumatlandırır (istiqamətləndirir)' },
  { code: 'GV.OC-02', name: 'Daxili və xarici maraqlı tərəflər başa düşülür, onların kibertəhlükəsizlik risklərinin idarə edilməsi ilə bağlı ehtiyac və gözləntiləri dərk edilir və nəzərə alınır' },
  { code: 'GV.OC-03', name: 'Kibertəhlükəsizliklə bağlı hüquqi, tənzimləyici və müqavilə tələbləri - cümlədən məxfilik və mülki azadlıqlar üzrə öhdəliklər başa düşülür və idarə olunur' },
  { code: 'GV.OC-04', name: 'Maraqlı tərəflərın təşkilatdan asılı olduğu və ya gözlədiyi kritik hədəflər, imkanlar və xidmətlər başa düşülür və kommunikasiya edilir (çatdırılır)' },
  { code: 'GV.OC-05', name: 'Təşkilatın asılı olduğu nəticələr, imkanlar və xidmətlər başa düşülür və kommunikasiya edilir (çatdırılır)' },
  { code: 'GV.RM-01', name: 'Risklərin idarə edilməsi hədəfləri təşkilati maraqlı tərəflər tərəfindən müəyyən edilir və razılaşdırılır' },
  { code: 'GV.RM-02', name: 'Risk iştahı və risk tolerantlığı bəyanatları müəyyən edilir, kommunikasiya edilir və saxlanılır (aktual tutulur)' },
  { code: 'GV.RM-03', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsi fəaliyyətləri və nəticələri müəssisə risklərinin idarə edilməsi (ERM) proseslərinə daxil edilir' },
  { code: 'GV.RM-04', name: 'Müvafiq riskə reaksiya variantlarını təsvir edən strateji istiqamət müəyyən edilir və kommunikasiya edilir' },
  { code: 'GV.RM-05', name: 'Təşkilat daxilində kibertəhlükəsizlik riskləri, o cümlədən təchizatçılardan və digər üçüncü tərəflərdən qaynaqlanan risklər üçün kommunikasiya xətləri qurulur' },
  { code: 'GV.RM-06', name: 'Kibertəhlükəsizlik risklərinin hesablanması, sənədləşdirilməsi, kateqoriyalara bölünməsi və prioritetləşdirilməsi üçün standartlaşdırılmış metod müəyyən edilir və kommunikasiya edilir' },
  { code: 'GV.RM-07', name: 'Strateji imkanlar (yəni, müsbət risklər) xarakterizə edilir və təşkilati kibertəhlükəsizlik riski müzakirələrinə daxil edilir' },
  { code: 'GV.RR-01', name: 'Təşkilati rəhbərlik kibertəhlükəsizlik riski üçün məsuliyyət və hesabatlılıq daşıyır və riskdən xəbərdar, etik və davamlı təkmilləşən bir mədəniyyəti təşviq edir' },
  { code: 'GV.RR-02', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsi ilə bağlı rollar, öhdəliklər və səlahiyyətlər müəyyən edilir, kommunikasiya edilir, başa düşülür və icra olunur' },
  { code: 'GV.RR-03', name: 'Kibertəhlükəsizlik riski strategiyasına, rollarına, öhdəliklərinə və siyasətlərinə mütənasib olaraq adekvat resurslar ayrılır' },
  { code: 'GV.RR-04', name: 'Kibertəhlükəsizlik insan resursları təcrübələrinə daxil edilir' },
  { code: 'GV.PO-01', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsi siyasəti təşkilati kontekst, kibertəhlükəsizlik strategiyası və prioritetləri əsasında müəyyən edilir, kommunikasiya edilir və icra olunur' },
  { code: 'GV.PO-02', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsi siyasəti tələblərdə, təhdidlərdə, texnologiyada və təşkilati missiyada baş verən dəyişiklikləri əks etdirmək üçün nəzərdən keçirilir, yenilənir, kommunikasiya edilir və icra olunur' },
  { code: 'GV.OV-01', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsi strategiyasının nəticələri strategiya və istiqaməti məlumatlandırmaq və tənzimləmək üçün nəzərdən keçirilir' },
  { code: 'GV.OV-02', name: 'Təşkilati tələblərin və risklərin əhatə olunmasını təmin etmək üçün kibertəhlükəsizlik risklərinin idarə edilməsi strategiyası nəzərdən keçirilir və tənzimlənir' },
  { code: 'GV.OV-03', name: 'Təşkilati kibertəhlükəsizlik risklərinin idarə edilməsi performansı qiymətləndirilir və tələb olunan tənzimləmələr üçün nəzərdən keçirilir' },
  { code: 'GV.SC-01', name: 'Kibertəhlükəsizlik təchizat zənciri risklərinin idarə edilməsi proqramı, strategiyası, hədəfləri, siyasətləri və prosesləri təşkilati maraqlı tərəflər tərəfindən müəyyən edilir və razılaşdırılır' },
  { code: 'GV.SC-02', name: 'Təchizatçılar, müştərilər və tərəfdaşlar üçün kibertəhlükəsizlik rolları və öhdəlikləri müəyyən edilir, kommunikasiya edilir və daxili, həmçinin xarici olaraq əlaqələndirilir' },
  { code: 'GV.SC-03', name: 'Kibertəhlükəsizlik təchizat zənciri risklərinin idarə edilməsi kibertəhlükəsizlik və müəssisə risklərinin idarə edilməsi, risklərin qiymətləndirilməsi və təkmilləşdirilmə proseslərinə inteqrasiya olunur' },
  { code: 'GV.SC-04', name: 'Təchizatçılar tanınr və kritiklik dərəcəsinə görə prioritetləşdirilir' },
  { code: 'GV.SC-05', name: 'Təchizat zəncirlərində kibertəhlükəsizlik risklərinin həll edilməsi tələbləri müəyyən edilir, prioritetləşdirilir və təchizatçılar və digər müvafiq üçüncü tərəflərlə bağlanan müqavilələrə və digər növ razılaşmalara inteqrasiya olunur' },
  { code: 'GV.SC-06', name: 'Rəsmi təchizatçı və ya digər üçüncü tərəf münasibətlərinə başlamazdan əvvəl riskləri azaltmaq üçün planlaşdırma və lazımi araşdırma (due diligence) həyata keçirilir' },
  { code: 'GV.SC-07', name: 'Təchizatçı, onların məhsul və xidmətləri, həmçinin digər üçüncü tərəflərin yaratdığı risklər münasibətlərin gedişatı ərzində başa düşülür, qeydə alınır, prioritetləşdirilir, qiymətləndirilir, onlara reaksiya verilir və monitorinq edilir' },
  { code: 'GV.SC-08', name: 'Müvafiq təchizatçılar və digər üçüncü tərəflər insidentlərin planlaşdırılması, reaksiya verilməsi və bərpası fəaliyyətlərinə daxil edilir' },
  { code: 'GV.SC-09', name: 'Təchizat zəncirinin təhlükəsizliyi təcrübələri kibertəhlükəsizlik və müəssisə risklərinin idarə edilməsi proqramlarına inteqrasiya olunur və onların performansı texnoloji məhsul və xidmət ömrü boyu (life cycle) monitorinq edilir' },
  { code: 'GV.SC-10', name: 'Kibertəhlükəsizlik təchizat zənciri risklərinin idarə edilməsi planları tərəfdaşlıq və ya xidmət müqaviləsi başa çatdıqdan sonra baş verən fəaliyyətlər üçün müddəaları ehtiva edir' },
  { code: 'ID.AM-01', name: 'Təşkilat tərəfindən idarə olunan aparat təminatının inventarları saxlanılır (aktual tutulur)' },
  { code: 'ID.AM-02', name: 'Təşkilat tərəfindən idarə olunan proqram təminatı, xidmətlər və sistemlərin inventarları saxlanılır (aktual tutulur)' },
  { code: 'ID.AM-03', name: 'Təşkilatın icazə verilmiş şəbəkə kommunikasiyasının və daxili, həmçinin xarici şəbəkə data (məlumat) axınlarının təsvirləri saxlanılır (aktual tutulur)' },
  { code: 'ID.AM-04', name: 'Təchizatçılar tərəfindən göstərilən xidmətlərin inventarları saxlanılır (aktual tutulur)' },
  { code: 'ID.AM-05', name: 'Aktivlər təsnifata, kritikliyə, resurslara və missiyaya göstərdiyi təsirə əsasən prioritetləşdirilir' },
  { code: 'ID.AM-07', name: 'Təyin edilmiş data növləri üçün datanın və müvafiq metadata-nın (meta-məlumatların) inventarları saxlanılır (aktual tutulur)' },
  { code: 'ID.AM-08', name: 'Sistemlər, aparat təminatı, proqram təminatı, xidmətlər və data öz həyat dövləri (life cycles) boyu idarə olunur' },
  { code: 'ID.RA-01', name: 'Aktivlərdəki boşluqlar (vulnerabilities) müəyyən edilir, yoxlanılır (təsdiqlənir) və qeydə alınır' },
  { code: 'ID.RA-02', name: 'İnformasiya mübadiləsi forumlarından və mənbələrindən kiber təhdid kəşfiyyatı (cyber threat intelligence) qəbul edilir' },
  { code: 'ID.RA-03', name: 'Təşkilata yönəlmiş daxili və xarici təhdidlər müəyyən edilir və qeydə alınır' },
  { code: 'ID.RA-04', name: 'Təhdidlərin boşluqlardan (vulnerabilities) istifadə etməsinin potensial təsirləri və ehtimalları müəyyən edilir və qeydə alınır' },
  { code: 'ID.RA-05', name: 'Mövcud (inharent) riski başa düşmək və riskə reaksiya prioritetlərini müəyyənləşdirmək üçün təhdidlərdən, boşluqlardan, ehtimallardan və təsirlərdən istifadə olunur' },
  { code: 'ID.RA-06', name: 'Riskə reaksiyalar seçilir, prioritetləşdirilir, planlaşdırılır, izlənilir və kommunikasiya edilir' },
  { code: 'ID.RA-07', name: 'Dəyişikliklər və istisnalar idarə olunur, risk təsirləri qiymətləndirilir, qeydə alınır və izlənilir' },
  { code: 'ID.RA-08', name: 'Boşluqların (vulnerability) aşkarlanması barədə məlumatların qəbulu, təhlili və onlara reaksiya verilməsi üçün proseslər qurulur' },
  { code: 'ID.RA-09', name: 'Aparat və proqram təminatının həqiqiliyi və bütövlüyü satınalma və istifadədən əvvəl qiymətləndirilir' },
  { code: 'ID.RA-10', name: 'Kritik təchizatçılar satınalmadan əvvəl qiymətləndirilir' },
  { code: 'ID.IM-01', name: 'Qiymətləndirmələrdən (evaluations) təkmilləşdirmələr müəyyən edilir' },
  { code: 'ID.IM-02', name: 'Təhlükəsizlik testləri və təlimlərindən (o cümlədən təchizatçılar və müvafiq üçüncü tərəflərlə koordinasiyalı şəkildə edilənlərdən) təkmilləşdirmələr müəyyən edilir' },
  { code: 'ID.IM-03', name: 'Əməliyyat proseslərinin, prosedurlarının və fəaliyyətlərinin icrasından təkmilləşdirmələr müəyyən edilir' },
  { code: 'ID.IM-04', name: 'İnsidentlərə reaksiya planları və əməliyyatlara təsir edən digər kibertəhlükəsizlik planları qurulur, kommunikasiya edilir, saxlanılır (aktual tutulur) və təkmilləşdirilir' },
  { code: 'PR.AA-01', name: 'Səlahiyyətli istifadəçilər, xidmətlər və aparat təminatı üçün şəxsiyyətlər (identities) və etibarnamələr (credentials) təşkilat tərəfindən idarə olunur' },
  { code: 'PR.AA-02', name: 'Şəxsiyyətlər yoxlanılır (proofed) və qarşılıqlı əlaqə kontekstinə əsasən etibarnamələrə (credentials) bağlanır' },
  { code: 'PR.AA-03', name: 'İstifadəçilər, xidmətlər və aparat təminatı autentifikasiya edilir (eyniləşdirilir)' },
  { code: 'PR.AA-04', name: 'Şəxsiyyət təsdiqləri (identity assertions) qorunur, ötürülür və yoxlanılır' },
  { code: 'PR.AA-05', name: 'Giriş icazələri, hüquqları və səlahiyyətləri siyasətdə müəyyən edilir, idarə olunur, icra edilir və nəzərdən keçirilir, həmçinin ən az imtiyaz (least privilege) və vəzifələrin bölünməsi (separation of duties) prinsiplərini ehtiva edir' },
  { code: 'PR.AA-06', name: 'Aktivlərə fiziki giriş riskə mütənasib olaraq idarə olunur, monitorinq edilir və icra olunur' },
  { code: 'PR.AT-01', name: 'Heyət, kibertəhlükəsizlik risklərini nəzərə alaraq ümumi tapşırıqları yerinə yetirmək üçün bilik və bacarıqlara sahib olmaq məqsədilə maarifləndirmə və təlimlərlə təmin edilir' },
  { code: 'PR.AT-02', name: 'İxtisaslaşdırılmış rollardakı fərdlər, kibertəhlükəsizlik risklərini nəzərə alaraq müvafiq tapşırıqları yerinə yetirmək üçün bilik və bacarıqlara sahib olmaq məqsədilə maarifləndirmə və təlimlərlə təmin edilir' },
  { code: 'PR.DS-01', name: 'Saxlanılan datanın (data-at-rest) məxfiliyi, bütövlüyü və əlçatanlığı qorunur' },
  { code: 'PR.DS-02', name: 'Ötürülən datanın (data-in-transit) məxfiliyi, bütövlüyü və əlçatanlığı qorunur' },
  { code: 'PR.DS-10', name: 'İstifadə olunan datanın (data-in-use) məxfiliyi, bütövlüyü və əlçatanlığı qorunur' },
  { code: 'PR.DS-11', name: 'Datanın ehtiyat nüsxələri (backups) yaradılır, qorunur, saxlanılır və test edilir' },
  { code: 'PR.PS-01', name: 'Konfiqurasiya idarəetməsi (configuration management) təcrübələri müəyyən edilir və tətbiq olunur' },
  { code: 'PR.PS-02', name: 'Proqram təminatı riskə mütənasib olaraq saxlanılır, dəyişdirilir və silinir' },
  { code: 'PR.PS-03', name: 'Aparat təminatı riskə mütənasib olaraq saxlanılır, dəyişdirilir və silinir' },
  { code: 'PR.PS-04', name: 'Davamlı monitorinq üçün loq qeydləri (log records) generasiya edilir və əlçatan edilir' },
  { code: 'PR.PS-05', name: 'Səlahiyyətsiz proqram təminatının quraşdırılması və icrasının qarşısı alınır' },
  { code: 'PR.PS-06', name: 'Təhlükəsiz proqram təminatının hazırlanması təcrübələri inteqrasiya olunur və onların performansı proqram təminatının hazırlanması həyat dövri (SDLC) boyu monitorinq edilir' },
  { code: 'PR.IR-01', name: 'Şəbəkələr və mühitlər icazəsiz məntiqi girişdən və istifadədən qorunur' },
  { code: 'PR.IR-02', name: 'Təşkilatın texnoloji aktivləri ətraf mühit təhdidlərindən qorunur' },
  { code: 'PR.IR-03', name: 'Normal və əlverişsiz vəziyyətlərdə davamlılıq (resilience) tələblərinə nail olmaq üçün mexanizmlər tətbiq edilir' },
  { code: 'PR.IR-04', name: 'Əlçatanlığı təmin etmək üçün adekvat resurs tutumu (capacity) saxlanılır' },
  { code: 'DE.CM-01', name: 'Şəbəkələr və şəbəkə xidmətləri potensial əlverişsiz hadisələri tapmaq üçün monitorinq edilir' },
  { code: 'DE.CM-02', name: 'Fiziki mühit potensial əlverişsiz hadisələri tapmaq üçün monitoring edilir' },
  { code: 'DE.CM-03', name: 'Heyətin fəaliyyəti və texnologiyadan istifadəsi potensial əlverişsiz hadisələri tapmaq üçün monitorinq edilir' },
  { code: 'DE.CM-06', name: 'Xarici xidmət provayderlərinin fəaliyyətləri və xidmətləri potensial əlverişsiz hadisələri tapmaq üçün monitorinq edilir' },
  { code: 'DE.CM-09', name: 'Hesablama aparat və proqram təminatı, iş mühitləri (runtime environments) və onların dataları potensial əlverişsiz hadisələri tapmaq üçün monitorinq edilir' },
  { code: 'DE.AE-02', name: 'Potensial əlverişsiz hadisələr, əlaqəli fəaliyyətləri daha yaxşı başa düşmək üçün təhlil edilir' },
  { code: 'DE.AE-03', name: 'Çoxsaylı mənbələrdən gələn məlumatlar korrelyasiya edilir (əlaqələndirilir)' },
  { code: 'DE.AE-04', name: 'Əlverişsiz hadisələrin təxmin edilən təsiri və miqyası başa düşülür' },
  { code: 'DE.AE-06', name: 'Əlverişsiz hadisələr barədə məlumatlar səlahiyyətli heyətə və alətlərə ötürülür' },
  { code: 'DE.AE-07', name: 'Kiber təhdid kəşfiyyatı və digər kontekstual məlumatlar təhlilə inteqrasiya olunur' },
  { code: 'DE.AE-08', name: 'Əlverişsiz hadisələr müəyyən edilmiş insident kriteriyalarına cavab verdikdə insidentlər elan edilir' },
  { code: 'RS.MA-01', name: 'İnsident elan edildikdən sonra insidentlərə reaksiya planı müvafiq üçüncü tərəflərlə koordinasiyalı şəkildə icra olunur' },
  { code: 'RS.MA-02', name: 'İnsident hesabatları çeşidlənir (triage) və yoxlanılır (təsdiqlənir)' },
  { code: 'RS.MA-03', name: 'İnsidentlər kateqoriyalara bölünür və prioritetləşdirilir' },
  { code: 'RS.MA-04', name: 'İnsidentlər tələb olunduqda eskalasiya edilir (yuxarı mərhələyə ötürülür) və ya dərəcəsi qaldırılır' },
  { code: 'RS.MA-05', name: 'İnsidentdən sonra bərpa prosesinə başlamaq üçün kriteriyalar tətbiq olunur' },
  { code: 'RS.AN-03', name: 'İnsident zamanı nələrin baş verdiyini və insidentin köklü səbəbini (root cause) müəyyən etmək üçün təhlil aparılır' },
  { code: 'RS.AN-06', name: 'Araşdırma zamanı yerinə yetirilən hərəkətlər qeydə alınır, qeydlərin bütövlüyü və mənşəyi (provenance) qorunur' },
  { code: 'RS.AN-07', name: 'İnsident datası və metadata toplanır, onların bütövlüyü və mənşəyi (provenance) qorunur' },
  { code: 'RS.AN-08', name: 'İnsidentin böyüklüyü (miqyası) təxmin edilir və yoxlanılır' },
  { code: 'RS.CO-02', name: 'Daxili və xarici maraqlı tərəflər insidentlər barədə məlumatlandırılır' },
  { code: 'RS.CO-03', name: 'İnformasiya təyin olunmuş daxili və xarici maraqlı tərəflərlə paylaşılır' },
  { code: 'RS.MI-01', name: 'İnsidentlər lokallaşdırılır (təcrid edilir/contain olunur)' },
  { code: 'RS.MI-02', name: 'Insidentlər tamamilə aradan qaldırılır (kökü kəsilir/eradicated olunur)' },
  { code: 'RC.RP-01', name: 'İnsidentə reaksiya prosesindən başladıldıqdan sonra insidentə reaksiya planının bərpa hissəsi icra olunur' },
  { code: 'RC.RP-02', name: 'Bərpa hərəkətləri seçilir, miqyası müəyyən edilir, prioritetləşdirilir və yerinə yetirilir' },
  { code: 'RC.RP-03', name: 'Ehtiyat nüsxələrin (backups) və digər bərpa aktivlərinin bütövlüyü onlardan bərpa üçün istifadə etməzdən əvvəl yoxlanılır' },
  { code: 'RC.RP-04', name: 'İnsidentdən sonrakı əməliyyat normalarını müəyyən etmək üçün kritik missiya funksiyaları və kibertəhlükəsizlik risklərinin idarə edilməsi nəzərə alınır' },
  { code: 'RC.RP-05', name: 'Bərpa edilmiş aktivlərin bütövlüyü yoxlanılır, sistemlər və xidmətlər bərpa edilir və normal fəaliyyət statusu təsdiqlənir' },
  { code: 'RC.RP-06', name: 'Kriteriyalara əsasən insidentdən bərpanın başa çatması elan edilir və insidentlə bağlı sənədləşdirmə tamamlanır' },
  { code: 'RC.CO-03', name: 'Bərpa fəaliyyətləri və əməliyyat imkanlarının bərpası istiqamətindəki irəliləyişlər təyin olunmuş daxili və xarici maraqlı tərəflərə kommunikasiya edilir (çatdırılır)' },
  { code: 'RC.CO-04', name: 'Insidentdən bərpa barədə ictimai yeniləmələr təsdiqlənmiş metodlar və mesajlaşma vasitəsilə paylaşılır' }
];