export const nistData = [
  { code: 'GV.OC-01', name: 'Təşkilatın missiyası başa düşülür və kibertəhlükəsizlik risklərinin idarə edilməsini məlumatlandırır' },
  { code: 'GV.OC-02', name: 'Daxili və xarici maraqlı tərəflər tanınır, onların kibertəhlükəsizlik risklərinin idarə edilməsi ilə bağlı ehtiyac və gözləntiləri başa düşülür və nəzərə alınır' },
  { code: 'GV.OC-03', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsinə dair hüquqi, tənzimləyici və müqavilə öhdəlikləri başa düşülür və idarə olunur' },
  { code: 'GV.OC-04', name: 'Təşkilatın öz missiyasını davam etdirməsi üçün zəruri olan kritik nəticələr, funksiyalar, xidmətlər və infrastruktur elementləri müəyyən edilir və prioritetləşdirilir' },
  { code: 'GV.OC-05', name: 'Asılılıqların əsaslandığı nəticələr, funksiyalar, xidmətlər və infrastruktur elementləri müəyyən edilir və prioritetləşdirilir' },
  { code: 'GV.RM-01', name: 'Kibertəhlükəsizlik risklərinin idarə edilməsi hədəfləri, prioritetləri, məhdudiyyətləri, risk tolerantlığı və fərziyyələri müəyyən edilir və kommunikasiya olunur' },
  { code: 'GV.RM-02', name: 'Risklərin idarə edilməsi seçimləri və təkmilləşdirmələr strateji məqsədlər, prioritetlər, məhdudiyyətlər və risk iştahı bəyanatları ilə istiqamətləndirilir' },
  { code: 'GV.RM-03', name: 'Kiber risklərin qiymətləndirilməsi prosesləri və nəticələri risklərin idarə edilməsinin strateji, operativ və taktiki səviyyələrinə inteqrasiya olunur' },
  { code: 'GV.RR-01', name: 'Təşkilati rəhbərlik kibertəhlükəsizlik risklərinin idarə edilməsinə görə cavabdehlik və məsuliyyət daşıyır' },
  { code: 'GV.RR-02', name: 'Kibertəhlükəsizlik rolları, öhdəlikləri və səlahiyyətləri aydın şəkildə müəyyən edilir, kommunikasiya olunur və başa düşülür' },
  { code: 'GV.RR-03', name: 'Kiber risklərin idarə edilməsi prioritetləri, nəticələri və problemləri təşkilat daxilində kommunikasiya olunur' },
  { code: 'GV.RR-04', name: 'Əsas rəhbərlər və maraqlı tərəflər öz kibertəhlükəsizlik öhdəliklərini və məsuliyyətlərini başa düşürlər' },
  { code: 'GV.PO-01', name: 'Təşkilati kibertəhlükəsizlik siyasətləri müəyyən edilir, yenilənir və kommunikasiya olunur' },
  { code: 'GV.PO-02', name: 'Təşkilat miqyasında kibertəhlükəsizlik siyasətləri dövri olaraq və əhəmiyyətli təşkilati və xarici dəyişikliklərdən sonra nəzərdən keçirilir və yenilənir' },
  { code: 'GV.OV-01', name: 'Strateji qərarların qəbul edilməsini təmin etmək üçün təşkilat miqyasında kibertəhlükəsizlik risklərinin idarə edilməsi fəaliyyətlərinin nəticələri və performansı rəhbərlik tərəfindən nəzərdən keçirilir' },
  { code: 'GV.OV-02', name: 'Performansın ölçülməsi və nəzarət fəaliyyətlərinin nəticələrinə əsasən kibertəhlükəsizlik risklərinin idarə edilməsi strategiyasına düzəlişlər edilir' },
  { code: 'GV.SC-01', name: 'Kibertəhlükəsizlik təchizat zənciri risklərinin idarə edilməsi (C-SCRM) proqramı qurulur, inteqrasiya olunur və saxlanılır' },
  { code: 'GV.SC-02', name: 'Təchizatçılar və tərəfdaşlar üçün kibertəhlükəsizlik tələbləri müqavilələrə və razılaşmalara inteqrasiya edilir' },
  { code: 'GV.SC-03', name: 'Təchizatçılar və tərəfdaşlar təşkilat üçün kritikliklərinə və potensial risklərinə əsasən qiymətləndirilir və prioritetləşdirilir' },
  { code: 'GV.SC-04', name: 'Təchizatçıların və tərəfdaşların kibertəhlükəsizlik performansı münasibətlərin bütün həyat dövrü boyu monitorinq edilir' },
  { code: 'GV.SC-05', name: 'Təchizat zəncirinin risklərinin idarə edilməsi təcrübələri təşkilati risklərin idarə edilməsi proseslərinə inteqrasiya olunur' },
  { code: 'ID.AM-01', name: 'Fiziki və virtual platformalar, cihazlar və proqram təminatı aktivlərinin inventarı aparılır və idarə olunur' },
  { code: 'ID.AM-02', name: 'Proqram təminatı aktivləri və tətbiqlərinin həyat dövrləri boyu inventarı aparılır və idarə olunur' },
  { code: 'ID.AM-03', name: 'Data emalı fəaliyyətlərini başa düşmək üçün data axınları və repozitoriyaları xəritələnir və inventarlaşdırılır' },
  { code: 'ID.AM-04', name: 'Təşkilat tərəfindən istifadə olunan xarici informasiya sistemləri və xidmətləri müəyyən edilir və prioritetləşdirilir' },
  { code: 'ID.AM-05', name: 'Resurslar təsnifatına, kritikliyə və biznes dəyərinə əsasən prioritetləşdirilir' },
  { code: 'ID.RA-01', name: 'Aktivlərdəki boşluqlar (zəifliklər) müəyyən edilir, təsdiqlənir və qeydə alınır' },
  { code: 'ID.RA-02', name: 'Kiber təhdid kəşfiyyatı qəbul edilir, təhlil edilir və risklərin qiymətləndirilməsində istifadə olunur' },
  { code: 'ID.RA-03', name: 'Daxili və xarici kiber təhdidlər müəyyən edilir və sənədləşdirilir' },
  { code: 'ID.RA-04', name: 'Kiber hadisələrin potensial təsirləri və başvermə ehtimalları qiymətləndirilir' },
  { code: 'ID.RA-05', name: 'Kiber risklər risklərin qiymətləndirilməsi nəticələrinə əsasən prioritetləşdirilir' },
  { code: 'ID.IM-01', name: 'Kibertəhlükəsizlik təkmilləşdirmələri qiymətləndirmələr, auditlər və real hadisələrdən çıxarılan dərslər əsasında müəyyən edilir' },
  { code: 'ID.IM-02', name: 'Müəyyən edilmiş boşluqları aradan qaldırmaq üçün təkmilləşdirmə planları hazırlanır, prioritetləşdirilir və icra edilir' },
  { code: 'PR.AA-01', name: 'Səlahiyyətli istifadəçilər, cihazlar və proseslər üçün identifikatorlar və etibarnamələr həyat dövrü boyu idarə olunur' },
  { code: 'PR.AA-02', name: 'Giriş icazələri minimum imtiyaz prinsiplərinə və vəzifələrin bölünməsinə əsasən verilir' },
  { code: 'PR.AA-03', name: 'İstifadəçilər, cihazlar və proseslər əməliyyatın risk dərəcəsinə uyğun olaraq autentifikasiya edilir' },
  { code: 'PR.AA-04', name: 'Giriş loqları qeydə alınır, monitorinq edilir və nəzərdən keçirilir' },
  { code: 'PR.AT-01', name: 'Bütün istifadəçilər kibertəhlükəsizlik üzrə maarifləndirmə təlimləri ilə təmin olunurlar' },
  { code: 'PR.AT-02', name: 'Xüsusi kibertəhlükəsizlik rolları olan personala ixtisaslaşdırılmış təlimlər keçirilir' },
  { code: 'PR.DS-01', name: 'Dincələn vəziyyətdəki data (data-at-rest) qorunur' },
  { code: 'PR.DS-02', name: 'Tranzit vəziyyətdəki data (data-in-transit) qorunur' },
  { code: 'PR.DS-03', name: 'Data bütövlüyü texniki və prosedural nəzarət vasitələri ilə təmin edilir' },
  { code: 'PR.PS-01', name: 'İT aktivləri üçün konfiqurasiya idarəetməsi proseslərindən istifadə olunur' },
  { code: 'PR.PS-02', name: 'Məlum boşluqların təsirini azaltmaq üçün proqram təminatı yenilənir və yamalar tətbiq edilir' },
  { code: 'PR.IR-01', name: 'Şəbəkə kommunikasiyaları riskə əsaslanaraq qorunur və seqmentləşdirilir' },
  { code: 'PR.IR-02', name: 'Ekoloji və fiziki infrastruktur təhlükəsizliyi nəzarət vasitələri tətbiq olunur' },
  { code: 'DE.CM-01', name: 'Hadisələri aşkar etmək üçün şəbəkələr, sistemlər və mühitlər monitorinq edilir' },
  { code: 'DE.CM-02', name: 'İcazəsiz girişləri müəyyən etmək üçün aktivlər monitorinq edilir' },
  { code: 'DE.AE-01', name: 'Hadisələrin kiber insident olub-olmadığı müəyyən edilməsi üçün təhlil aparılır' },
  { code: 'DE.AE-02', name: 'Təhlil nəticələrindən planları təkmilləşdirmək üçün istifadə olunur' },
  { code: 'RS.MA-01', name: 'İnsidentlərə cavab tədbirləri planları hazırlanır və icra edilir' },
  { code: 'RS.MA-02', name: 'İnsidentlərə cavab qrupu təlim keçir və avadanlıqlarla təmin olunur' },
  { code: 'RS.AN-01', name: 'İnsidentlərin təsirini və kök səbəbini anlamaq üçün araşdırmalar aparılır' },
  { code: 'RS.AN-02', name: 'Kompüter ekspertizası (forensics) prosesləri həyata keçirilir' },
  { code: 'RS.CO-01', name: 'İnsidentlər barədə daxili maraqlı tərəflərə məlumat verilir' },
  { code: 'RS.CO-02', name: 'İnsidentlər xarici maraqlı tərəflərə və tənzimləyici qurumlara hesabat verilir' },
  { code: 'RS.MI-01', name: 'Kiber insidentlərin genişlənməsini məhdudlaşdırmaq üçün tədbirlər görülür' },
  { code: 'RS.MI-02', name: 'Təkrar olunmanın qarşısını almaq üçün boşluqlar aradan qaldırılır' },
  { code: 'RC.RP-01', name: 'Təsirlənmiş sistemləri bərpa etmək üçün bərpa planları icra edilir' },
  { code: 'RC.RP-02', name: 'Bərpa fəaliyyətləri kritiklik dərəcəsinə əsasən prioritetləşdirilir' },
  { code: 'RC.CO-01', name: 'Bərpa prosesinin gedişatı daxili maraqlı tərəflərə bildirilir' },
  { code: 'RC.CO-02', name: 'İctimai yeniliklər təsdiqlənmiş üsullarla paylaşılır' },
];
