export const nistDataEn = [
  { code: 'GV.OC-01', name: 'The organizational mission is understood and informs cybersecurity risk management' },
  { code: 'GV.OC-02', name: 'Internal and external stakeholders are understood, and their needs and expectations regarding cybersecurity risk management are understood and considered' },
  { code: 'GV.OC-03', name: 'Legal, regulatory, and contractual requirements regarding cybersecurity - including privacy and civil liberties obligations - are understood and managed' },
  { code: 'GV.OC-04', name: 'Critical objectives, capabilities, and services that stakeholders depend on or expect from the organization are understood and communicated' },
  { code: 'GV.OC-05', name: 'Outcomes, capabilities, and services that the organization depends on are understood and communicated' },
  { code: 'GV.RM-01', name: 'Risk management objectives are established and agreed to by organizational stakeholders' },
  { code: 'GV.RM-02', name: 'Risk appetite and risk tolerance statements are established, communicated, and maintained' },
  { code: 'GV.RM-03', name: 'Cybersecurity risk management activities and outcomes are included in enterprise risk management processes' },
  { code: 'GV.RM-04', name: 'Strategic direction that describes appropriate risk response options is established and communicated' },
  { code: 'GV.RM-05', name: 'Lines of communication across the organization are established for cybersecurity risks, including risks from suppliers and other third parties' },
  { code: 'GV.RM-06', name: 'A standardized method for calculating, documenting, categorizing, and prioritizing cybersecurity risks is established and communicated' },
  { code: 'GV.RM-07', name: 'Strategic opportunities (i.e., positive risks) are characterized and are included in organizational cybersecurity risk discussions' },
  { code: 'GV.RR-01', name: 'Organizational leadership is responsible and accountable for cybersecurity risk and fosters a culture that is risk-aware, ethical, and continually improving' },
  { code: 'GV.RR-02', name: 'Roles, responsibilities, and authorities related to cybersecurity risk management are established, communicated, understood, and enforced' },
  { code: 'GV.RR-03', name: 'Adequate resources are allocated commensurate with the cybersecurity risk strategy, roles, responsibilities, and policies' },
  { code: 'GV.RR-04', name: 'Cybersecurity is included in human resources practices' },
  { code: 'GV.PO-01', name: 'Policy for managing cybersecurity risks is established based on organizational context, cybersecurity strategy, and priorities and is communicated and enforced' },
  { code: 'GV.PO-02', name: 'Policy for managing cybersecurity risks is reviewed, updated, communicated, and enforced to reflect changes in requirements, threats, technology, and organizational mission' },
  { code: 'GV.OV-01', name: 'Cybersecurity risk management strategy outcomes are reviewed to inform and adjust strategy and direction' },
  { code: 'GV.OV-02', name: 'The cybersecurity risk management strategy is reviewed and adjusted to ensure coverage of organizational requirements and risks' },
  { code: 'GV.OV-03', name: 'Organizational cybersecurity risk management performance is evaluated and reviewed for adjustments needed' },
  { code: 'GV.SC-01', name: 'A cybersecurity supply chain risk management program, strategy, objectives, policies, and processes are established and agreed to by organizational stakeholders' },
  { code: 'GV.SC-02', name: 'Cybersecurity roles and responsibilities for suppliers, customers, and partners are established, communicated, and coordinated internally and externally' },
  { code: 'GV.SC-03', name: 'Cybersecurity supply chain risk management is integrated into cybersecurity and enterprise risk management, risk assessment, and improvement processes' },
  { code: 'GV.SC-04', name: 'Suppliers are known and prioritized by criticality' },
  { code: 'GV.SC-05', name: 'Requirements to address cybersecurity risks in supply chains are established, prioritized, and integrated into contracts and other types of agreements with suppliers and other relevant third parties' },
  { code: 'GV.SC-06', name: 'Planning and due diligence are performed to reduce risks before entering into formal supplier or other third-party relationships' },
  { code: 'GV.SC-07', name: 'The risks posed by a supplier, their products and services, and other third parties are understood, recorded, prioritized, assessed, responded to, and monitored over the course of the relationship' },
  { code: 'GV.SC-08', name: 'Relevant suppliers and other third parties are included in incident planning, response, and recovery activities' },
  { code: 'GV.SC-09', name: 'Supply chain security practices are integrated into cybersecurity and enterprise risk management programs, and their performance is monitored throughout the technology product and service life cycle' },
  { code: 'GV.SC-10', name: 'Cybersecurity supply chain risk management plans include provisions for activities that occur after the conclusion of a partnership or service agreement' },
  { code: 'ID.AM-01', name: 'Inventories of hardware managed by the organization are maintained' },
  { code: 'ID.AM-02', name: 'Inventories of software, services, and systems managed by the organization are maintained' },
  { code: 'ID.AM-03', name: 'Representations of the organization’s authorized network communication and internal and external network data flows are maintained' },
  { code: 'ID.AM-04', name: 'Inventories of services provided by suppliers are maintained' },
  { code: 'ID.AM-05', name: 'Assets are prioritized based on classification, criticality, resources, and impact on the mission' },
  { code: 'ID.AM-07', name: 'Inventories of data and corresponding metadata for designated data types are maintained' },
  { code: 'ID.AM-08', name: 'Systems, hardware, software, services, and data are managed throughout their life cycles' },
  { code: 'ID.RA-01', name: 'Vulnerabilities in assets are identified, validated, and recorded' },
  { code: 'ID.RA-02', name: 'Cyber threat intelligence is received from information sharing forums and sources' },
  { code: 'ID.RA-03', name: 'Internal and external threats to the organization are identified and recorded' },
  { code: 'ID.RA-04', name: 'Potential impacts and likelihoods of threats exploiting vulnerabilities are identified and recorded' },
  { code: 'ID.RA-05', name: 'Threats, vulnerabilities, likelihoods, and impacts are used to understand inherent risk and inform risk response prioritization' },
  { code: 'ID.RA-06', name: 'Risk responses are chosen, prioritized, planned, tracked, and communicated' },
  { code: 'ID.RA-07', name: 'Changes and exceptions are managed, assessed for risk impact, recorded, and tracked' },
  { code: 'ID.RA-08', name: 'Processes for receiving, analyzing, and responding to vulnerability disclosures are established' },
  { code: 'ID.RA-09', name: 'The authenticity and integrity of hardware and software are assessed prior to acquisition and use' },
  { code: 'ID.RA-10', name: 'Critical suppliers are assessed prior to acquisition' },
  { code: 'ID.IM-01', name: 'Improvements are identified from evaluations' },
  { code: 'ID.IM-02', name: 'Improvements are identified from security tests and exercises, including those done in coordination with suppliers and relevant third parties' },
  { code: 'ID.IM-03', name: 'Improvements are identified from execution of operational processes, procedures, and activities' },
  { code: 'ID.IM-04', name: 'Incident response plans and other cybersecurity plans that affect operations are established, communicated, maintained, and improved' },
  { code: 'PR.AA-01', name: 'Identities and credentials for authorized users, services, and hardware are managed by the organization' },
  { code: 'PR.AA-02', name: 'Identities are proofed and bound to credentials based on the context of interactions' },
  { code: 'PR.AA-03', name: 'Users, services, and hardware are authenticated' },
  { code: 'PR.AA-04', name: 'Identity assertions are protected, conveyed, and verified' },
  { code: 'PR.AA-05', name: 'Access permissions, entitlements, and authorizations are defined in a policy, managed, enforced, and reviewed, and incorporate the principles of least privilege and separation of duties' },
  { code: 'PR.AA-06', name: 'Physical access to assets is managed, monitored, and enforced commensurate with risk' },
  { code: 'PR.AT-01', name: 'Personnel are provided with awareness and training so that they possess the knowledge and skills to perform general tasks with cybersecurity risks in mind' },
  { code: 'PR.AT-02', name: 'Individuals in specialized roles are provided with awareness and training so that they possess the knowledge and skills to perform relevant tasks with cybersecurity risks in mind' },
  { code: 'PR.DS-01', name: 'The confidentiality, integrity, and availability of data-at-rest are protected' },
  { code: 'PR.DS-02', name: 'The confidentiality, integrity, and availability of data-in-transit are protected' },
  { code: 'PR.DS-10', name: 'The confidentiality, integrity, and availability of data-in-use are protected' },
  { code: 'PR.DS-11', name: 'Backups of data are created, protected, maintained, and tested' },
  { code: 'PR.PS-01', name: 'Configuration management practices are established and applied' },
  { code: 'PR.PS-02', name: 'Software is maintained, replaced, and removed commensurate with risk' },
  { code: 'PR.PS-03', name: 'Hardware is maintained, replaced, and removed commensurate with risk' },
  { code: 'PR.PS-04', name: 'Log records are generated and made available for continuous monitoring' },
  { code: 'PR.PS-05', name: 'Installation and execution of unauthorized software are prevented' },
  { code: 'PR.PS-06', name: 'Secure software development practices are integrated, and their performance is monitored throughout the software development life cycle' },
  { code: 'PR.IR-01', name: 'Networks and environments are protected from unauthorized logical access and usage' },
  { code: 'PR.IR-02', name: 'The organization’s technology assets are protected from environmental threats' },
  { code: 'PR.IR-03', name: 'Mechanisms are implemented to achieve resilience requirements in normal and adverse situations' },
  { code: 'PR.IR-04', name: 'Adequate resource capacity to ensure availability is maintained' },
  { code: 'DE.CM-01', name: 'Networks and network services are monitored to find potentially adverse events' },
  { code: 'DE.CM-02', name: 'The physical environment is monitored to find potentially adverse events' },
  { code: 'DE.CM-03', name: 'Personnel activity and technology usage are monitored to find potentially adverse events' },
  { code: 'DE.CM-06', name: 'External service provider activities and services are monitored to find potentially adverse events' },
  { code: 'DE.CM-09', name: 'Computing hardware and software, runtime environments, and their data are monitored to find potentially adverse events' },
  { code: 'DE.AE-02', name: 'Potentially adverse events are analyzed to better understand associated activities' },
  { code: 'DE.AE-03', name: 'Information is correlated from multiple sources' },
  { code: 'DE.AE-04', name: 'The estimated impact and scope of adverse events are understood' },
  { code: 'DE.AE-06', name: 'Information on adverse events is provided to authorized staff and tools' },
  { code: 'DE.AE-07', name: 'Cyber threat intelligence and other contextual information are integrated into the analysis' },
  { code: 'DE.AE-08', name: 'Incidents are declared when adverse events meet the defined incident criteria' },
  { code: 'RS.MA-01', name: 'The incident response plan is executed in coordination with relevant third parties once an incident is declared' },
  { code: 'RS.MA-02', name: 'Incident reports are triaged and validated' },
  { code: 'RS.MA-03', name: 'Incidents are categorized and prioritized' },
  { code: 'RS.MA-04', name: 'Incidents are escalated or elevated as needed' },
  { code: 'RS.MA-05', name: 'The criteria for initiating incident recovery are applied' },
  { code: 'RS.AN-03', name: 'Analysis is performed to establish what has taken place during an incident and the root cause of the incident' },
  { code: 'RS.AN-06', name: 'Actions performed during an investigation are recorded, and the records’ integrity and provenance are preserved' },
  { code: 'RS.AN-07', name: 'Incident data and metadata are collected, and their integrity and provenance are preserved' },
  { code: 'RS.AN-08', name: 'An incident’s magnitude is estimated and validated' },
  { code: 'RS.CO-02', name: 'Internal and external stakeholders are notified of incidents' },
  { code: 'RS.CO-03', name: 'Information is shared with designated internal and external stakeholders' },
  { code: 'RS.MI-01', name: 'Incidents are contained' },
  { code: 'RS.MI-02', name: 'Incidents are eradicated' },
  { code: 'RC.RP-01', name: 'The recovery portion of the incident response plan is executed once initiated from the incident response process' },
  { code: 'RC.RP-02', name: 'Recovery actions are selected, scoped, prioritized, and performed' },
  { code: 'RC.RP-03', name: 'The integrity of backups and other restoration assets is verified before using them for restoration' },
  { code: 'RC.RP-04', name: 'Critical mission functions and cybersecurity risk management are considered to establish post-incident operational norms' },
  { code: 'RC.RP-05', name: 'The integrity of restored assets is verified, systems and services are restored, and normal operating status is confirmed' },
  { code: 'RC.RP-06', name: 'The end of incident recovery is declared based on criteria, and incident-related documentation is completed' },
  { code: 'RC.CO-03', name: 'Recovery activities and progress in restoring operational capabilities are communicated to designated internal and external stakeholders' },
  { code: 'RC.CO-04', name: 'Public updates on incident recovery are shared using approved methods and messaging' }
];